name: MEEP Scanner
author: moreeyesplz
description: 'Scans commit messages for MEEPs and submits them'
runs:
  using: 'node12'
  main: 'meep_scanner.js'
inputs:
  github_token:
    description: 'GITHUB_TOKEN provided as a secret from Github'
    required: true
branding:
  icon: eye
  color: purple